flathub/org.darktable.Darktable

org.darktable.Darktable.json
=> Add support to talk to GVFS

org.darktable.Darktable.json
=> Update to 2.4.4

org.darktable.Darktable.json
- Also change download URL for Exiv2
=> Update darktable to 2.6.0

openexr-no-docs.patch, org.darktable.Darktable.json
This fixes the following issues:
* Issue #4 (supercede PR #24)
* Issue #21 
* Issue #25 
* Issue #27
=> Add missing dependencies

org.darktable.Darktable.json
=> Fix #30: update to 2.6.1

org.darktable.Darktable.json
=> Grant access to xdg-run/gvfs

add-rating-and-releases.patch, flathub.json, org.darktable.Darktable.json
Also integrates the changes from #46.
=> Update to 3.0

org.darktable.Darktable.json
=> Support colord

darktable-appdata.patch, org.darktable.Darktable.json
- Use libusb from shared-modules
- Added libavif (new)
=> New upstream 3.2.1

org.darktable.Darktable.json
=> Issue #64 - Build codec for libavif

org.darktable.Darktable.json
Please give it a test. (Works here)
Thanks!
=> Update to GNOME 3.38 runtime

org.darktable.Darktable.json
=> Issue #66 - Script Manager now works

darktable-appdata.patch, org.darktable.Darktable.json
Builds and runs fine. Dependencies are still the same.
=> Bump version to 3.6.1

darktable-aarch64.patch, darktable-appdata.patch, lua5.4/lua-5.4.json, lua5.4/lua.pc.in, lua5.4/makefile-add-liblua.so-rule.patch, org.darktable.Darktable.json
- Update runtime to GNOME 41
- Update exiv2
- Added Jasper and libheif
=> Update to 3.8.0

org.darktable.Darktable.json
=> Update lensfun to 0.3.3 and update the hash for the database repo.

darktable-appdata.patch, org.darktable.Darktable.json
=> Issue #91 - Darktable 4.0.0

org.darktable.Darktable.json
=> Issue #102 - update libheif

org.darktable.Darktable.json
- added libsoup-2.4
- updated exiv2 to 0.27.6
=> Update runtime to GNOME 44

org.darktable.Darktable.json
Lensfun has data for a bunch of new lenses.  This should add them to the build.
=> update lensfun database

org.darktable.Darktable.json
- Also update GraphicsMagick and libheif
=> Update to GNOME 45

org.darktable.Darktable.json
Update to latest exiv2 library.
=> Update exiv2 to version 28.3

org.darktable.Darktable.json
=> Allow org.darktable.service D-Bus

org.darktable.Darktable.json
=> Update runtime to GNOME 46

org.darktable.Darktable.json
Update GNOME runtime from 47 to 48.
=> Update GNOME runtime from 47 to 48.

org.darktable.Darktable.json
This is #138 rebased.
Close #138
=> Include exiv2 command line tool in sandbox
